config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

root :to => 'posts#index'
resources :user_sessions
resources :users do
  member do
    get :user_posts, to: 'users#user_posts'
    get :user_comments, to: 'users#user_comments'
    get :user_likes, to: 'users#user_likes'
  end
end

resources :password_resets, only: [:create, :update, :edit, :new]

resources :posts do
  collection do
    get :best, to: 'posts#best'
    get :most_recent, to: 'posts#most_recent'
    put :up_vote, to: 'posts#up_vote'
    put :down_vote, to: 'posts#down_vote'
    put :neutral_vote, to: 'posts#neutral_vote'
    get :search, to: 'posts#search'
  end
end

resources :tags, only: [:show] do
  member do
    put :add_to_blacklist
  end
end

resources :comments do
  collection do
    put :up_vote, to: 'comments#up_vote'
    put :down_vote, to: 'comments#down_vote'
    put :neutral_vote, to: 'comments#neutral_vote'
    get 'parent_comment/:code', to: 'comments#parent_comment'
    get 'comment_tree/:code', to: 'comments#comment_tree'
  end
end

resources :profiles, only: [] do
  collection do
    get :my_posts, to: 'profiles#my_posts'
    get :my_comments, to: 'profiles#my_comments'
    get :up_voted, to: 'profiles#up_voted'
    get :settings, to: 'profiles#settings'
    post :change_settings, to: 'profiles#change_settings'
    post :change_password, to: 'profiles#change_password'
    get :social_net_ctrl, to: 'profiles#social_net_ctrl'
  end
end

resources :admins, only: [] do
  collection do
    get :users, to: 'admins#users'
    put :ban_user, to: 'admins#ban_user'
  end
end

post "oauth/callback" => "oauths#callback"
get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

get '*path', to: redirect('/')
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_filter :require_login, :find_user, :set_title

  def my_posts
    @posts = @user.posts.where(published: true)
  end

  def my_comments
    @comments = @user.comments.joins(:post).merge(Post.where(published: true)).order("created_at DESC")
  end

  def up_voted
    @posts = @user.get_up_voted Post
  end

  def settings
    authentications = @user.authentications
    @fb = authentications.where(provider: 'facebook')
    @vk = authentications.where(provider: 'vk')
  end

  def change_settings
    unless validate_change_params(params)
      flash[:alert] = @message
      return redirect_to action: 'settings'
    end
    @user.email = params['email']
    @user.nick = params['nick']
    @user.avatar = save_user_avatar(params[:avatar], @user.folder, @user.avatar, params[:image_square]) if params[:avatar]
    @user.save(validate: false)
    redirect_to action: 'settings'
  end

  def change_password
    if params['old-pass'].present?
      check_pass_confirmation
      if @user.password == params['old-pass']
        update_pass
      else
        flash[:alert] = 'Невірний пароль'
        return redirect_to(settings_profiles_path)
      end
    else
      if @user.crypted_password.present?
        check_pass_confirmation
        update_pass
      else
        update_pass
      end
    end
  end

  def social_net_ctrl
    if params['remove'].present?
      if params['remove'] == 'vk'
        @user.authentications.where(provider: 'vk').first.destroy
      else
        @user.authentications.where(provider: 'facebook').first.destroy
      end
    end
    redirect_to settings_profiles_path
  end

  private

  def update_pass
    @user.password = params['new-pass']
    @user.save(validate: false)
    flash[:alert] = 'Пароль успішно змінений'
    redirect_to action: 'settings'
  end

  def check_pass_confirmation
    unless params['new-pass'] == params['new-pass-confirm']
      flash[:alert] = 'Підтвердження пароля не збіглось'
      redirect_to action: 'settings'
    end
  end

  def validate_change_params(data)
    res = true
    unless (3..10).include?(data['nick'].length)
      @message = 'Формат ніка невірний'
      res = false
    end
    unless data['email'] =~ /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
      @message = 'Формат емейла невірний'
      res = false
    end
    res
  end

  def find_user
    @user = current_user
    @votes = @user.votes
  end
    
  def set_title
    @page_title = 'профайл'
  end

  def save_user_avatar(image_data, folder, old_name, square)
    image = Magick::Image.from_blob(image_data.read).first
    resize = square.split(",")
    image.crop!(resize[0].to_i, resize[1].to_i, resize[2].to_i, resize[3].to_i)
    image.resize_to_fit!(120)
    name = Digest::MD5.hexdigest(folder + Time.now.to_s) + "." + image.format
    image.write(Rails.root.join("public/content/avatars/" + folder + "/" + name))
    image.resize_to_fit!(50)
    image.write(Rails.root.join("public/content/avatars/" + folder + "/thumb_" + name))
    if old_name
      File.delete(Rails.root.join("public/content/avatars/" + folder + "/" + old_name))
      File.delete(Rails.root.join("public/content/avatars/" + folder + "/thumb_" + old_name))
    end
    name
  end
end

app/helpers/profiles_helper.rb
module ProfilesHelper
  def date_diff(date)
    res = Time.diff(Time.now, date , '%y, %d')
    res[:diff]
  end

  def active_page(item_index)
  	active = " navigation-item-active".html_safe
  	case item_index
  	when 1
  	  controller.action_name == "my_posts" ? active : ""
  	when 2
  	  controller.action_name == "my_comments" ? active : ""
  	when 3
  	  controller.action_name == "up_voted" ? active : ""
  	when 4
  	  controller.action_name == "settings" ? active : ""
  	end
  end
end

app/views/profiles/_image_cut.html.erb
<div id="image-cut" class="modal fade builder-modal">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
              <h4 class="modal-title">Виділіть область зобреження</h4>
            </div>
            <div class="modal-body clearfix">
              <div class="col-xs-12 col-md-12">
                <div class="image-cut-panel" data-conf="">
                  <div class="image-selector" data-x="0" data-y="0"><div class="image-selector-resize"></div></div>
                  <img id="image-cut-foto" src="javascript:void(0);" />
                </div>
              </div>
            </div>
            <div class="modal-footer">
              <button type="button" id="image-cut-submit" class="btn btn-primary">Готово</button>
            </div>
        </div>
    </div>
</div>

app/views/profiles/_my_comment.html.erb
<div class="col-xs-8 col-md-8 profile-comment">
  <div class="profile-user-comment" data-code="<%= comment.code %>">
    <div class="profile-comment-head">
      <span class="profile-rating-comment"><%= item_rating(comment) %></span>
       додано до <%= link_to comment.post.title, comment.post%> 
      <% if comment.parent_id %>
       відповідь користувачеві <%= link_to "@" + comment.receiver.nick, user_posts_user_path(comment.receiver.nick)%>
      <% end %>
    </div>
    <div class="profile-comment-body">
      <div class="profile-comment-text"><%= comment.com_body %></div>
      <% if comment.comment_img %>
        <img class="comment-body-img" src="<%= comment.comment_img %>" width="300" />
      <% end %>
    </div>
    <div class="profile-comment-actions">
      <a href="javascript:void(0);" class="profile-comment-show-tree">відповіді</a>
      <% if comment.parent_id %>
        <a href="javascript:void(0);" class="profile-comment-show-parent">батьківський</a>
      <% end %>
      <% unless current_user.id == comment.user.id %>
        <%= display_plus_minus_comment(comment) %>
      <% end %>
    </div>
  </div>
</div>

app/views/profiles/_profile_head.html.erb
<div class="profile_head col-xs-12">
  <div class="profile_head_panel"></div>
  <div class="profile-user-info">
    <div class="avatar">
      <img class="profile-user-avatar-preview img-circle" width="120" src="<%= get_user_avatar(@user) %>"/>
    </div>
    <div class="avatar-column"></div>
    <div class="profile-user-data">
      <div class="user_name"><%= @user.nick %></div>
      <div class="profile-user-activity">
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-stats"></span>
          <span class="profile-user-activity-item-text">Рейтинг</span>
          <div class="profile-user-activity-item-quantity"><%= @user.rating %></div>
        </div>
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-file"></span>
          <span class="profile-user-activity-item-text">Пости</span>
          <div class="profile-user-activity-item-quantity"><%= @user.posts.length %></div>
        </div>
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-comment"></span>
          <span class="profile-user-activity-item-text">Коменти</span>
          <div class="profile-user-activity-item-quantity"><%= @user.comments.length %></div>
        </div>
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-thumbs-up"></span>
          <span class="profile-user-activity-item-text">Аплодував</span>
          <div class="profile-user-activity-item-quantity"><%= @votes.where(vote_flag: 1).length %></div>
        </div>
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-thumbs-down"></span>
          <span class="profile-user-activity-item-text">Проти</span>
          <div class="profile-user-activity-item-quantity"><%= @votes.where(vote_flag: 0).length %></div>
        </div>
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-calendar"></span>
          <span class="profile-user-activity-item-text">На сайті</span>
          <div class="profile-user-activity-item-quantity"><%= date_diff(@user.created_at) %></div>
        </div>
      </div>    
    </div>
    <div class="profile-user-navigation">
      <div class="profile-user-navigation-item<%= active_page(1) %>">
        <div class="navigation-item-circle-block">
          <div class="navigation-item-circle"></div>
        </div>
        <div class="navigation-item-text-block">
          <%= link_to 'Мої пости', my_posts_profiles_path %>
        </div>
      </div>
      <div class="profile-user-navigation-item<%= active_page(2) %>">
        <div class="navigation-item-circle-block">
          <div class="navigation-item-circle"></div>
        </div>
        <div class="navigation-item-text-block">
          <%= link_to 'Мої Коментарі', my_comments_profiles_path %>
        </div>
      </div>
      <div class="profile-user-navigation-item<%= active_page(3) %>">
        <div class="navigation-item-circle-block">
          <div class="navigation-item-circle"></div>
        </div>
        <div class="navigation-item-text-block">
          <%= link_to 'Вподобані пости', up_voted_profiles_path %>
        </div>
      </div>
      <div class="profile-user-navigation-item<%= active_page(4) %>">
        <div class="navigation-item-circle-block">
          <div class="navigation-item-circle"></div>
        </div>
        <div class="navigation-item-text-block">
          <%= link_to 'Налаштування', settings_profiles_path %>
        </div>
      </div>

    </div>
  </div>

  <div id="nav">
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
</div>

app/views/profiles/my_comments.html.erb
<div class="profile">
  <%= render 'profile_head'%>
  <div id="profile_comments">
      <%= form_tag "", id: "form_1", class: 'new_comment hidden' do %>
	    <div class="form-group">
        <input type="hidden" class="comment-current-post" value="">
        <input type="hidden" class="comment-parent-comment" value="">
	    <textarea class='comment-com-body form-control' value=""></textarea>
	    </div>
	    <div class="add-comment-buttons col-xs-12">
	      <div class="from-comment-attachment" data-img=""><span>Нічого не прикріплено</span>
	        <i class="dismiss-comment-attachment glyphicon glyphicon-remove hidden"></i>  
	      </div>
	      <button type="button" class="btn btn-danger send_comment">Додати</button>
	      <button type="button" class="btn btn-default add-comment-image">Прикріпити зображення</button>
	    </div>
	  <% end %>
    <%= render partial: 'my_comment', collection: @comments, as: :comment %>
  </div>
</div>

app/views/profiles/my_posts.html.erb
<div class="profile">
  <%= render 'profile_head'%>
  <%= render @posts%>
</div>

app/views/profiles/settings.html.erb
<div class="profile">
  <%= render 'profile_head'%>
  <div id="profile_settings" class="settings">
    <ul class="nav nav-pills nav-stacked col-xs-3" id="left_nav">
      <li class="active"><a href="#profile" data-toggle="tab">Профіль</a></li>
      <li><a href="#password" data-toggle="tab">Змінити пароль</a></li>
      <li><a href="#social" data-toggle="tab">Соціальні мережі</a></li>
    </ul>
    <div class="tab-content">
        <div class="settings_profile tab-pane active col-xs-9" id="profile">
          <%= form_tag(change_settings_profiles_path, :class => 'form-horizontal', :multipart => true) do %>
            <%= field_set_tag "Профіль" do %>
              <div class="form-group">
                <label class="control-label col-xs-11" for="avatar">Аватар</label>
                <div class="col-xs-2">
                  <img id="avatar_preview" width="120" src="<%= get_user_avatar(@user) %>"/>
                </div>
                <div class="col-xs-4 profile-avatar-input">
                  <span class="btn btn-default btn-file"><span>Вибрати</span><input type="file" id="avatar" class="form-control" name="avatar"></span>
                  <div class="profile-avatar-description">PNG або JPG, максимальний розмір: 2MB</div>
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-xs-11" for="nick">Нік</label>
                <div class="profile-input-line">
                  <input type="text" class="form-control" id="nick" placeholder="Введіть нік" name="nick" value="<%= @user.nick%>">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-xs-11" for="email">Електронна пошта</label>
                <div class="profile-input-line">
                  <input type="email" class="form-control" id="email" placeholder="Введіть електронну пошту"
                         name="email" value=" <%= @user.email%> ">
                </div>
              </div>
              <input type="hidden" id="image_square" name="image_square" value="">
              <div class="form-group">
                <div class="col-xs-8">
                  <button type="submit" class="btn btn-primary">Змінити</button>
                </div>
              </div>
            <% end %>  
          <% end %>
          <%= render 'image_cut'%>
        </div>

        <div class="settings_reset tab-pane col-xs-9" id="password">
          <%= form_tag(change_password_profiles_path, :class => 'form-horizontal') do %>
            <%= field_set_tag "Змінити пароль" do %>
              <% if @user.crypted_password%>
                  <div class="form-group">
                    <label class="control-label col-xs-11" for="old-pass">Поточний пароль</label>
                    <div class="profile-input-line">
                      <input type="password" class="form-control" id="old-pass" placeholder="Введіть поточний пароль" name="old-pass">
                    </div>
                  </div>
              <% end %>
              <div class="form-group">
                <label class="control-label col-xs-11" for="new-pass">Новий пароль</label>
                <div class="profile-input-line">
                  <input type="password" class="form-control" id="new-pass" placeholder="Введіть новий пароль" name="new-pass">
                </div>
              </div>
              <div class="form-group">
                <label class="control-label col-xs-11" for="new-pass-confirm">Повторіть новий пароль</label>
                <div class="profile-input-line">
                  <input type="password" class="form-control" id="new-pass-confirm" placeholder="Введіть новий пароль" name="new-pass-confirm">
                </div>
              </div>
              <div class="form-group">
                <div class="col-xs-8">
                  <button type="submit" class="btn btn-primary">Змінити</button>
                </div>
              </div>
            <% end %>
          <% end %>
        </div>

        <div class="settings_social tab-pane col-xs-9" id="social">
          <%= field_set_tag "Під'єднати соціальні мережі" do %>
            <div class="connect-soccial-network-table">
              <div class="warning_soc_networks">
                Під'єднайте ваші соціальні аккаунти, щоб мати змогу виконувати<br>вхід на сайт з їхньою допомогою.
              </div>
              <div class="soccial-table-item">
                <div class="connect-soccial-item">
                  <i class="connect-icon fb-icon"></i>
                  <div class="soccial-item-title">Під'єднати ваший Facebook аккаунт</div>
                  <div class="connect-button">
                    <% if @fb.empty? %>
                      <%= link_to "Під'єднати", auth_at_provider_path(:provider => :facebook), class: "btn btn-primary" %>
                    <% else %>
                      <%= link_to "Від'єднати", social_net_ctrl_profiles_path( remove: 'fb'), class: "btn btn-primary" %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="soccial-table-item">
                <div class="connect-soccial-item">
                  <i class="connect-icon vk-icon"></i>
                  <div class="soccial-item-title">Під'єднати ваший VK аккаунт</div>
                  <div class="connect-button">
                    <% if @vk.empty? %>
                      <%= link_to "Під'єднати", auth_at_provider_path(:provider => :vk), class: "btn btn-primary" %>
                    <% else %>
                      <%= link_to "Від'єднати", social_net_ctrl_profiles_path( remove: 'vk'), class: "btn btn-primary" %>
                    <% end %>
                  </div>
                </div>
              </div>
              <div class="soccial-table-item">
                <div class="connect-soccial-item">
                  <i class="connect-icon tw-icon"></i>
                  <div class="soccial-item-title">Під'єднати ваший Twitter аккаунт</div>
                  <div class="connect-button">
                      <%= link_to "Під'єднати", "javascript:void(0);", class: "btn btn-primary" %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
    </div>
  </div>
</div>

app/views/profiles/up_voted.html.erb
<div class="profile">
  <%= render 'profile_head'%>
  <%= render @posts%>
</div>