config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

root :to => 'posts#index'
resources :user_sessions
resources :users do
  member do
    get :user_posts, to: 'users#user_posts'
    get :user_comments, to: 'users#user_comments'
    get :user_likes, to: 'users#user_likes'
  end
end

resources :password_resets, only: [:create, :update, :edit, :new]

resources :posts do
  collection do
    get :best, to: 'posts#best'
    get :most_recent, to: 'posts#most_recent'
    put :up_vote, to: 'posts#up_vote'
    put :down_vote, to: 'posts#down_vote'
    put :neutral_vote, to: 'posts#neutral_vote'
    get :search, to: 'posts#search'
  end
end

resources :tags, only: [:show] do
  member do
    put :add_to_blacklist
  end
end

resources :comments do
  collection do
    put :up_vote, to: 'comments#up_vote'
    put :down_vote, to: 'comments#down_vote'
    put :neutral_vote, to: 'comments#neutral_vote'
    get 'parent_comment/:code', to: 'comments#parent_comment'
    get 'comment_tree/:code', to: 'comments#comment_tree'
  end
end

resources :profiles, only: [] do
  collection do
    get :my_posts, to: 'profiles#my_posts'
    get :my_comments, to: 'profiles#my_comments'
    get :up_voted, to: 'profiles#up_voted'
    get :settings, to: 'profiles#settings'
    post :change_settings, to: 'profiles#change_settings'
    post :change_password, to: 'profiles#change_password'
    get :social_net_ctrl, to: 'profiles#social_net_ctrl'
  end
end

resources :admins, only: [] do
  collection do
    get :users, to: 'admins#users'
    put :ban_user, to: 'admins#ban_user'
  end
end

post "oauth/callback" => "oauths#callback"
get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

get '*path', to: redirect('/')
end

app/views/menus/_main.html.erb
<nav id="menu_main" class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a href="<%= root_path %>"><img src="<%= get_main_logo %>" alt="logo" id="logo"></a>
    </div>
      <ul class="nav navbar-nav left_buttons">
        <li class= <%= "active" if current_page?(controller: 'posts', action: 'index') %> ><a href="<%= root_path %>">Гаряче</a></li>
        <li class= <%= "active" if current_page?(controller: 'posts', action: 'best') %> ><a href="<%= best_posts_path %>">Найкраще</a></li>
        <li class= <%= "active" if current_page?(controller: 'posts', action: 'most_recent') %> ><a href="<%= most_recent_posts_path %>">Нове</a></li>
        <li>
          <span class="dropdown-toggle tags_dropdown <%= 'active' if tags_nav_active? %> " data-toggle="dropdown" aria-expanded="true">
            Більше
          </span>
          <ul class="dropdown-menu" role="menu">
            <% @tags.each do |tag| %>
              <li class=<%= 'active' if tag_item_active?(tag.name) %>  role="presentation"><a role="menuitem" tabindex="-1" href="<%= tag_path(tag.name) %>"><%= tag.name %></a></li>
            <% end %>
          </ul>
        </li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <div class="right_buttons search_div">
            <div class="search_icon">
              <i class="glyphicon glyphicon-search" id="search_icon"></i>
            </div>
            <%= form_tag search_posts_path, :method => :get, id: 'search_form' do %>
              <input type="text" name="search" id="search">
              <i class="glyphicon glyphicon-search" id="search_submit"></i>
            <% end %>
          </div>
        </li>
        <li><a class="right_buttons" href="<%=  new_post_path %>"><i class="glyphicon glyphicon-plus"></i></a></li>
        <% if current_user %>
            <li><a class="right_buttons" href="<%= my_posts_profiles_path %>"><i class="glyphicon glyphicon-user"></i></a></li>
            <li><a class="right_buttons" href="<%= settings_profiles_path %>"><i class="glyphicon glyphicon-cog"></i></a></li>
        <% else %>
            <li><a role="button"  data-toggle="modal" class="right_buttons last_cell" id="user_actions" href="#"><i class="glyphicon glyphicon-log-in"></i></a></li>
        <% end %>
        <% if is_admin? %>
          <li><a class="right_buttons" href="<%= users_admins_path %>">admin</a></li>
        <% end %>
        <% if current_user %>
          <li>
            <%= link_to "", :logout, method: :post, class: "glyphicon glyphicon-log-out right_buttons last_cell" %>
          </li>
        <% end %>
      </ul>
  </div><!-- /.container-fluid -->
  <div class="bottom_line"></div>
</nav>