config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

root :to => 'posts#index'
resources :user_sessions
resources :users do
  member do
    get :user_posts, to: 'users#user_posts'
    get :user_comments, to: 'users#user_comments'
    get :user_likes, to: 'users#user_likes'
  end
end

resources :password_resets, only: [:create, :update, :edit, :new]

resources :posts do
  collection do
    get :best, to: 'posts#best'
    get :most_recent, to: 'posts#most_recent'
    put :up_vote, to: 'posts#up_vote'
    put :down_vote, to: 'posts#down_vote'
    put :neutral_vote, to: 'posts#neutral_vote'
    get :search, to: 'posts#search'
  end
end

resources :tags, only: [:show] do
  member do
    put :add_to_blacklist
  end
end

resources :comments do
  collection do
    put :up_vote, to: 'comments#up_vote'
    put :down_vote, to: 'comments#down_vote'
    put :neutral_vote, to: 'comments#neutral_vote'
    get 'parent_comment/:code', to: 'comments#parent_comment'
    get 'comment_tree/:code', to: 'comments#comment_tree'
  end
end

resources :profiles, only: [] do
  collection do
    get :my_posts, to: 'profiles#my_posts'
    get :my_comments, to: 'profiles#my_comments'
    get :up_voted, to: 'profiles#up_voted'
    get :settings, to: 'profiles#settings'
    post :change_settings, to: 'profiles#change_settings'
    post :change_password, to: 'profiles#change_password'
    get :social_net_ctrl, to: 'profiles#social_net_ctrl'
  end
end

resources :admins, only: [] do
  collection do
    get :users, to: 'admins#users'
    put :ban_user, to: 'admins#ban_user'
  end
end

post "oauth/callback" => "oauths#callback"
get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

get '*path', to: redirect('/')
end

app/models/user.rb
class User < ActiveRecord::Base
  authenticates_with_sorcery!
  require 'fileutils'

  authenticates_with_sorcery! do |config|
    config.authentications_class = Authentication
  end

  has_many :comments
  has_many :receivers, class_name: 'Comment', foreign_key: 'receiver_id'
  has_many :posts
  has_many :authentications, :dependent => :destroy
  has_one :blacklist
  accepts_nested_attributes_for :authentications

  acts_as_voter

  validates :password, length: { minimum: 5 }
  validates :password, confirmation: true
  validates :password_confirmation, presence: true

  validates :nick, presence: true, :uniqueness => {:case_sensitive => false}, length: { in: 3..10 },format: { with: /\w/ }
  validates :email, :uniqueness => {:case_sensitive => false}, presence: true,
            format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

  before_create do
    set_nick
    make_user_dir
  end

  def to_param
    nick
  end

  private

  def make_user_dir
    content_root =  Rails.root.join("public/content/")
    folder_created = Digest::MD5.hexdigest(id.to_s + Time.now.to_s)
    Dir.mkdir(content_root + "comments/" + folder_created)
    Dir.mkdir(content_root + "posts/" + folder_created)
    Dir.mkdir(content_root + "avatars/" + folder_created)
    self.folder = folder_created
  end

  def set_nick
    @nick = email.split('@').first.downcase[0..6]
    @nick.gsub!(/[^0-9A-Za-z]/, '')
    if @nick.empty?
      @nick = Translit.convert(email, :english)[0..6]
    end
    check_nick(@nick)
    self.nick = @nick
  end

  def check_nick(nick_d)
    if User.find_by_nick(nick_d)
      @nick = nick_d + SecureRandom.hex(1)
      check_nick(@nick)
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :check_owner, only: [:user_comments, :user_likes, :user_posts]
  
  def new
   @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.nick = "nick"
    if verify_recaptcha && @user.save
      auto_login(@user)
      redirect_to(root_url, notice: 'Юзер створений')
    else
      flash[:alert] = 'Помилка створення юзера'
      render :new
    end
  end

  def user_posts
    @posts = @user.posts
  end

  def user_comments
    @posts = Post.uniq.joins(:comments).where("comments.user_id = ?", @user.id)
  end

  def user_likes
    @posts = @user.get_up_voted Post
  end

  private

  def check_owner
    @user = current_user
    profile_user = User.find_by_nick(params[:id])
    @self = true if profile_user == @user
    if @self
      redirect_to my_posts_profiles_path
    else
      @user = profile_user
    end
    @votes = @user.votes
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/users_helper.rb
module UsersHelper
  def user_profile_active_page(item_index)
  	active = " navigation-item-active".html_safe
  	case item_index
  	when 1
  	  controller.action_name == "user_posts" ? active : ""
  	when 2
  	  controller.action_name == "user_comments" ? active : ""
  	when 3
  	  controller.action_name == "user_likes" ? active : ""
  	end
  end
end

app/views/users/_form.html.erb
<div class="field">
   <%= f.label :password %><br />
   <%= f.password_field :password %>
</div>
<div class="field">
   <%= f.label :password_confirmation %><br />
   <%= f.password_field :password_confirmation %>
</div>

app/views/users/_user_head.html.erb
<div class="profile_head col-xs-12">
  <div class="profile_head_panel"></div>
  <div class="profile-user-info">
    <div class="avatar">
      <img class="profile-user-avatar-preview img-circle" width="120" src="<%= get_user_avatar(@user) %>"/>
    </div>
    <div class="avatar-column"></div>
    <div class="profile-user-data">
      <div class="user_name"><%= @user.nick %></div>
      <div class="profile-user-activity">
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-stats"></span>
          <span class="profile-user-activity-item-text">Рейтинг</span>
          <div class="profile-user-activity-item-quantity"><%= @user.rating %></div>
        </div>
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-file"></span>
          <span class="profile-user-activity-item-text">Пости</span>
          <div class="profile-user-activity-item-quantity"><%= @user.posts.length %></div>
        </div>
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-comment"></span>
          <span class="profile-user-activity-item-text">Коменти</span>
          <div class="profile-user-activity-item-quantity"><%= @user.comments.length %></div>
        </div>
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-thumbs-up"></span>
          <span class="profile-user-activity-item-text">Аплодував</span>
          <div class="profile-user-activity-item-quantity"><%= @votes.where(vote_flag: 1).length %></div>
        </div>
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-thumbs-down"></span>
          <span class="profile-user-activity-item-text">Проти</span>
          <div class="profile-user-activity-item-quantity"><%= @votes.where(vote_flag: 0).length %></div>
        </div>
        <div class="profile-user-activity-item">
          <span class="glyphicon glyphicon-calendar"></span>
          <span class="profile-user-activity-item-text">На сайті</span>
          <div class="profile-user-activity-item-quantity"><%= date_diff(@user.created_at) %></div>
        </div>
      </div>    
    </div>
    <div class="profile-user-navigation">
      <div class="profile-user-navigation-item<%= user_profile_active_page(1) %>">
        <div class="navigation-item-circle-block">
          <div class="navigation-item-circle"></div>
        </div>
        <div class="navigation-item-text-block">
          <%= link_to 'Пости', user_posts_user_path %>
        </div>
      </div>
      <div class="profile-user-navigation-item<%= user_profile_active_page(2) %>">
        <div class="navigation-item-circle-block">
          <div class="navigation-item-circle"></div>
        </div>
        <div class="navigation-item-text-block">
          <%= link_to 'Коментував', user_comments_user_path %>
        </div>
      </div>
      <div class="profile-user-navigation-item<%= user_profile_active_page(3) %>">
        <div class="navigation-item-circle-block">
          <div class="navigation-item-circle"></div>
        </div>
        <div class="navigation-item-text-block">
          <%= link_to 'Аплодував', user_likes_user_path %>
        </div>
      </div>
    </div>
  </div>

  <div id="nav">
    <p id="notice"><%= flash[:notice] %></p>
    <p id="alert"><%= flash[:alert] %></p>
  </div>
</div>

app/views/users/new.html.erb
<div class="register_form">
  <div class="col-xs-12 register_head">
    Реєстрація
  </div>
  <%= form_for @user do |f| %>
    <div class="field">
      <%= f.label :email, 'Емейл' %>
      <%= f.text_field :email, class: "form-control"  %>
    </div>
    <div class="field">
      <%= f.label :password, 'Пароль' %>
      <%= f.password_field :password, class: "form-control" %>
    </div>
    <div class="field">
      <%= f.label :password_confirmation, 'Ще разок пароль' %>
      <%= f.password_field :password_confirmation, class: "form-control" %>

    </div>
      <%= recaptcha_tags %>
    <div class="button_div">
      <%= button_tag 'Зареєструватись', class: "btn sign_up_button"%>
    </div>
  <% end %>
</div>

app/views/users/user_comments.html.erb
<div class="profile">
  <%= render 'user_head'%>
  <%= render @posts%>
</div>

app/views/users/user_likes.html.erb
<div class="profile">
  <%= render 'user_head'%>
  <%= render @posts%>
</div>

app/views/users/user_posts.html.erb
<div class="profile">
  <%= render 'user_head'%>
  <%= render @posts%>
</div>