config/routes.rb
Rails.application.routes.draw do

  get 'password_resets/create'

  get 'password_resets/edit'

  get 'password_resets/update'

root :to => 'posts#index'
resources :user_sessions
resources :users do
  member do
    get :user_posts, to: 'users#user_posts'
    get :user_comments, to: 'users#user_comments'
    get :user_likes, to: 'users#user_likes'
  end
end

resources :password_resets, only: [:create, :update, :edit, :new]

resources :posts do
  collection do
    get :best, to: 'posts#best'
    get :most_recent, to: 'posts#most_recent'
    put :up_vote, to: 'posts#up_vote'
    put :down_vote, to: 'posts#down_vote'
    put :neutral_vote, to: 'posts#neutral_vote'
    get :search, to: 'posts#search'
  end
end

resources :tags, only: [:show] do
  member do
    put :add_to_blacklist
  end
end

resources :comments do
  collection do
    put :up_vote, to: 'comments#up_vote'
    put :down_vote, to: 'comments#down_vote'
    put :neutral_vote, to: 'comments#neutral_vote'
    get 'parent_comment/:code', to: 'comments#parent_comment'
    get 'comment_tree/:code', to: 'comments#comment_tree'
  end
end

resources :profiles, only: [] do
  collection do
    get :my_posts, to: 'profiles#my_posts'
    get :my_comments, to: 'profiles#my_comments'
    get :up_voted, to: 'profiles#up_voted'
    get :settings, to: 'profiles#settings'
    post :change_settings, to: 'profiles#change_settings'
    post :change_password, to: 'profiles#change_password'
    get :social_net_ctrl, to: 'profiles#social_net_ctrl'
  end
end

resources :admins, only: [] do
  collection do
    get :users, to: 'admins#users'
    put :ban_user, to: 'admins#ban_user'
  end
end

post "oauth/callback" => "oauths#callback"
get "oauth/callback" => "oauths#callback" # for use with Github, Facebook
get "oauth/:provider" => "oauths#oauth", :as => :auth_at_provider

get 'login' => 'user_sessions#new', :as => :login
post 'logout' => 'user_sessions#destroy', :as => :logout

get '*path', to: redirect('/')
end

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController
  skip_before_filter :require_login, except: [:destroy]

  def create
    if @user = login(params[:email], params[:password], params[:remember])
      redirect_back_or_to(root_url, notice: 'Успішно увійшли')
    else
      flash.now[:alert] = 'Помилка входу'
      redirect_to(root_url)
    end
  end

  def destroy
    logout
    redirect_to(root_url, notice: 'Успішно вийшли')
  end
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/user_sessions/_new.html.erb
<% @user = User.new %>
<div class="col-xs-6 left_part">
  <%= form_tag user_sessions_path, :method => :post do %>
    <div class="field">
      <%= label_tag :email, 'Емейл' %>
      <%= text_field_tag :email, nil, class: "form-control" %>
    </div>
    <br>
    <div class="field">
      <%= label_tag :password, 'Пароль' %>
      <%= password_field_tag :password, nil, class: "form-control" %>
    </div>
    <div class="actions">
      <%= button_tag 'Увійти', class: "btn sign_in_button"%>
      <span class="checkbox">
        <label>
          <input type="checkbox" name="remember" id="remember"> Запам'ятати мене
        </label>
      </span>
    </div>
  <% end %>
  <%= link_to 'Забув пароль?', new_password_reset_path %>
  <%= link_to "Зареєструватись", new_user_path, class: " register_link" %>
</div>

<div class="col-xs-6 right_part">
  <div class="connect_with">Увійдіть з</div>
  <div class="col-xs-12">
    <%= link_to auth_at_provider_path(:provider => :vk), class: "vk"  do %>
      <%= image_tag("social_networks_icons/vk.jpg", :alt => "vk", :class => "vk_image") %>
    <% end %>
    <%= link_to auth_at_provider_path(:provider => :facebook), class: ""  do %>
      <%= image_tag("social_networks_icons/fb.jpg", :alt => "fb", :class => "fb_image") %>
    <% end %>
    <%= link_to auth_at_provider_path(:provider => :twitter), class: ""  do %>
      <%= image_tag("social_networks_icons/tw.jpg", :alt => "tw", :class => "tw_image") %>
    <% end %>
  </div>
</div>